import { CheckCircle2, Clock3, History, LockKeyhole, Orbit, Shuffle, Sparkles, UserRoundCog, Users } from 'lucide-react'
import { useState } from 'react'
import { DocumentationPanel } from '../../features/documentation/components/DocumentationPanel'
import { RoleShell } from '../../shared/components/layout/RoleShell'

const names=['Laura','Daniel','Camila','Andrés','Sofía','Mateo','Valentina','Samuel','Sara','Nicolás','Mariana','Felipe']
const cellData=[['Cosmos','Juan','#a78bfa'],['B612','María','#fb7185'],['Asteroide','Carlos','#38bdf8'],['Zorro','Elena','#fbbf24']]

export function TlDashboardPage(){const[coders,setCoders]=useState(names);const[confirmed,setConfirmed]=useState(false);const shuffle=()=>{setConfirmed(false);setCoders(current=>[...current].sort(()=>Math.random()-.5))};return <RoleShell role="TL" name="Alex R."><header className="page-header page-header--premium"><div><div className="hero-kicker"><Sparkles size={14}/> Sprint 04 · Van Rossum</div><h1>Diseña la próxima tripulación</h1><p>Los líderes permanecen anclados. El sistema evita repetir célula mientras existan rutas posibles.</p></div><div className="header-actions"><button className="ghost-small"><History size={16}/> Historial</button><button className="primary-button" onClick={shuffle}><Shuffle size={17}/> Sortear coders</button></div></header><div className="rotation-summary"><div><Users/><span><strong>16</strong> coders asignados</span></div><div><Orbit/><span><strong>04</strong> células visibles</span></div><div><Clock3/><span><strong>6 días</strong> para iniciar</span></div><div className="rotation-valid"><CheckCircle2/><span>Reglas validadas</span></div></div><div className="rotation-grid rotation-grid--premium">{cellData.map(([cell,leader,color],index)=><article className="cell-card cell-card--premium" key={cell} style={{'--cell-color':color} as React.CSSProperties}><div className="cell-card__visual"><div className="cell-planet"><Orbit/></div><span>0{index+1}</span></div><div className="cell-card__header"><div><small>CÉLULA</small><h3>{cell}</h3></div><button title="Cambiar líder"><UserRoundCog size={17}/></button></div><div className="leader-row"><span><LockKeyhole size={14}/></span><div><small>LÍDER ANCLADO</small><strong>{leader}</strong></div></div><div className="crew-list">{coders.slice(index*3,index*3+3).map((name,position)=><div className="coder-row" key={name}><span style={{background:`linear-gradient(135deg,${color},#31244f)`}}>{name[0]}</span><div><strong>{name}</strong><small>Visitó {position+2} células</small></div><i>::</i></div>)}</div></article>)}</div><div className={`confirm-bar confirm-bar--premium ${confirmed?'is-confirmed':''}`}><div>{confirmed?<CheckCircle2/>:<Sparkles/>}<span><strong>{confirmed?'Rotación confirmada':'Distribución lista para revisar'}</strong><small>Sin repeticiones consecutivas · 1 líder y 3 rotadores por célula</small></span></div><button className="primary-button" onClick={()=>setConfirmed(true)}>{confirmed?'Confirmada ✓':'Confirmar rotación'}</button></div><DocumentationPanel/></RoleShell>}
