import { CircleCheck, CircleDashed, Clock3, MoreHorizontal, Plus, Rocket, ShieldCheck, Sparkles, UserRound } from 'lucide-react'
import { useState } from 'react'
import { RoleShell } from '../../shared/components/layout/RoleShell'

type Story={id:string;title:string;priority:string;avatar:string;points:number}
type Column={title:string;color:string;icon:typeof CircleCheck;cards:Story[]}
const initial:Column[]=[{title:'To Do',icon:CircleDashed,color:'#8b7fa8',cards:[{id:'HU-14',title:'Definir endpoints',priority:'Alta',avatar:'LM',points:5},{id:'HU-18',title:'Diseñar perfil',priority:'Media',avatar:'CT',points:3}]},{title:'In Progress',icon:Rocket,color:'#a78bfa',cards:[{id:'HU-11',title:'Modelo de cohortes',priority:'Alta',avatar:'DR',points:8},{id:'HU-20',title:'Landing B612',priority:'Alta',avatar:'LM',points:5}]},{title:'Review',icon:ShieldCheck,color:'#fb7185',cards:[{id:'HU-09',title:'Login por roles',priority:'Media',avatar:'CT',points:3}]},{title:'Done',icon:CircleCheck,color:'#5ce1b9',cards:[{id:'HU-03',title:'PostgreSQL',priority:'Alta',avatar:'DR',points:3},{id:'HU-01',title:'Estructura base',priority:'Media',avatar:'JL',points:2}]}]

export function LeaderDashboardPage(){
  const[columns,setColumns]=useState(initial)
  const[dragged,setDragged]=useState<{story:Story;from:string}|null>(null)
  const move=(target:string)=>{if(!dragged||dragged.from===target)return;setColumns(current=>current.map(column=>column.title===dragged.from?{...column,cards:column.cards.filter(card=>card.id!==dragged.story.id)}:column.title===target?{...column,cards:[...column.cards,dragged.story]}:column));setDragged(null)}
  const addStory=()=>setColumns(current=>current.map((column,index)=>index===0?{...column,cards:[...column.cards,{id:`HU-${21+column.cards.length}`,title:'Nueva historia de usuario',priority:'Media',avatar:'JL',points:3}]}:column))
  return <RoleShell role="Líder" name="Juan Líder"><header className="page-header page-header--premium"><div><div className="hero-kicker"><Sparkles size={14}/> Célula Cosmos · Sprint 04</div><h1>Tablero de misión</h1><p>Arrastra las historias para actualizar su estado.</p></div><button className="primary-button" onClick={addStory}><Plus size={17}/> Nueva historia</button></header><div className="sprint-pulse"><div><span>Progreso del sprint</span><strong>68%</strong></div><div className="pulse-progress"><i/></div><div className="pulse-team"><div className="avatar-stack">{['JL','LM','DR','CT'].map(x=><span key={x}>{x}</span>)}</div><span>4 tripulantes activos</span></div></div><div className="kanban kanban--premium">{columns.map(({icon:Icon,...column})=><section className="kanban-column" key={column.title} style={{'--column-color':column.color} as React.CSSProperties} onDragOver={event=>event.preventDefault()} onDrop={()=>move(column.title)}><header><div><Icon size={17}/><h3>{column.title}</h3></div><span>{column.cards.length}</span></header>{column.cards.map(card=><article draggable onDragStart={()=>setDragged({story:card,from:column.title})} className="story-card story-card--premium" key={card.id}><div className="story-top"><small>{card.id}</small><button><MoreHorizontal size={16}/></button></div><strong>{card.title}</strong><span className={`priority priority--${card.priority.toLowerCase()}`}>{card.priority}</span><div className="story-footer"><span className="avatar-mini"><UserRound size={13}/>{card.avatar}</span><span><Clock3 size={13}/>{card.points} pts</span></div></article>)}</section>)}</div></RoleShell>
}
