import { ArrowUpRight, Building2, GraduationCap, Orbit, Plus, Users } from 'lucide-react'
import { useState } from 'react'
import { RoleShell } from '../../shared/components/layout/RoleShell'

const metrics = [{value:'02',label:'Campus',detail:'Medellín · Barranquilla',icon:Building2,color:'violet'},{value:'04',label:'Cohortes',detail:'+1 este trimestre',icon:GraduationCap,color:'coral'},{value:'08',label:'Clanes',detail:'Todos activos',icon:Orbit,color:'cyan'},{value:'128',label:'Coders',detail:'94% participación',icon:Users,color:'mint'}]

export function AdminDashboardPage() {
  const[showCreate,setShowCreate]=useState(false)
  const[created,setCreated]=useState(false)
  return <RoleShell role="Admin" name="Ana Admin"><header className="page-header page-header--premium"><div><p className="eyebrow">Pulso de la organización</p><h1>Centro de control</h1><p>Una lectura clara de todo el universo académico.</p></div><button className="primary-button" onClick={()=>setShowCreate(true)}><Plus size={17}/> Crear cohorte</button></header><div className="metric-grid metric-grid--premium">{metrics.map(({icon:Icon,...metric})=><article className={`metric-card metric-card--${metric.color}`} key={metric.label}><div><Icon/><span>↗ 12%</span></div><strong>{metric.value}</strong><h3>{metric.label}</h3><p>{metric.detail}</p></article>)}</div><div className="admin-grid"><section className="data-panel data-panel--premium"><div className="section-heading"><div><p className="eyebrow">Estructura</p><h2>Cohortes recientes</h2></div><button className="text-button">Ver todas <ArrowUpRight size={16}/></button></div><table><thead><tr><th>Cohorte</th><th>Campus</th><th>Clanes</th><th>Coders</th><th>Estado</th></tr></thead><tbody><tr><td><b>Cohorte 6</b><small>Frontend · Backend</small></td><td>Medellín</td><td>4</td><td>64</td><td><span className="badge badge--green">Activa</span></td></tr><tr><td><b>Cohorte 7</b><small>Ruta avanzada</small></td><td>Barranquilla</td><td>4</td><td>64</td><td><span className="badge badge--gold">Preparación</span></td></tr>{created&&<tr><td><b>Cohorte 8</b><small>Nueva ruta</small></td><td>Medellín</td><td>0</td><td>0</td><td><span className="badge badge--gold">Preparación</span></td></tr>}</tbody></table></section><aside className="activity-card"><div><p className="eyebrow">Actividad</p><h2>Ritmo semanal</h2></div><div className="bar-chart">{[42,68,54,82,73,91,64].map((height,index)=><span key={index} style={{height:`${height}%`}}><i/></span>)}</div><div className="chart-labels"><span>L</span><span>M</span><span>M</span><span>J</span><span>V</span><span>S</span><span>D</span></div><div className="activity-stat"><strong>1,248</strong><span>acciones registradas</span></div></aside></div>{showCreate&&<div className="modal-backdrop" onMouseDown={()=>setShowCreate(false)}><form className="modal-card" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();setCreated(true);setShowCreate(false)}}><p className="eyebrow">Nueva estructura</p><h2>Crear cohorte</h2><label>Nombre<input defaultValue="Cohorte 8"/></label><label>Campus<select><option>Medellín</option><option>Barranquilla</option></select></label><label>Fecha de inicio<input type="date"/></label><div><button type="button" className="ghost-small" onClick={()=>setShowCreate(false)}>Cancelar</button><button className="primary-button">Crear cohorte</button></div></form></div>}</RoleShell>
}
